import Head from "next/head"
import Image from "next/image"

export default function Home() {
  return (
    <div className="flex flex-col h-full">
      <Head>
        <title>NextJS and Tailwind Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center h-full gap-5 lg:flex-row lg:justify-center">
        <div className="flex flex-col items-center gap-5 py-10 lg:flex-row lg:justify-center md:items-center lg:items-center">
          <img
            src="illustration-mockups.svg"
            alt=""
            className="w-full h-auto md:max-w-2xl lg:w-3/5 "
          />
          <div className="flex flex-col justify-center gap-5 lg:w-2/5 item-center lg:gap-10 md:justify-center lg:justify-start md:items-center lg:items-start ">
            <h1 className="text-2xl font-semibold leading-9 tracking-widest text-center text-white lg:leading-normal lg:text-5xl lg:text-left font-openSans">
              Build The Community Your Fans Will Love
            </h1>
            <p className="leading-7 tracking-wide text-center text-white lg:leading-normal lg:text-left font-openSans lg:text-2xl lg:font-normal">
              Huddle re-imagines the way we build communities. You have a voice,
              but so does your audience. Create connections with your users as
              you engage in genuine discussion.
            </p>
            <a
              href="#"
              className="py-3 text-center duration-150 bg-white rounded-full shadow-lg md:w-9/12 font-openSans text-violet hover:text-white hover:bg-softMagenta"
            >
              Register
            </a>
          </div>
        </div>
      </main>
    </div>
  )
}
